[env]
CI = ''
BASE_URL = "cubething.dev"
CONTENT_DIRECTORY = "content/main"
OUTPUT_DIRECTORY = "out/main/public"
NODE_OPTIONS = "--max-old-space-size=4096"

[tools]
node = "22.15.0"

[tasks]
deploy = 'npx quartz build -v'
watch = 'npx quartz build --watch'
