[env]
MAIN_DOTENV = "env/main.env"
EXAMPLE_DOTENV = "env/example.env"
CI = ''

[tools]
node = "22.15.0"

[tasks]
deploy_main = 'npx dotenvx run -f $MAIN_DOTENV -- npx quartz build'
serve_main = 'npx dotenvx run -f $MAIN_DOTENV -- npx quartz build --watch --serve'
deploy_example = 'npx dotenvx run -f $EXAMPLE_DOTENV -- npx quartz build'
